### ISSUE TITLE
support

### ISSUE THREAD

**Issue by rin1015** [Wicloz/Anime-Sentinel#2]
Can i host in my web.. Its is kind of streaming websites?

**Comment by Wicloz** [comment]
It's indeed a streaming site, already live here: https://anime.wilcodeboer.me/

**Comment by rin1015** [comment]
Can you give me tutorial to install this website into vps?

**Comment by Wicloz** [comment]
It uses Laravel so after cloning the repo this: https://laravel.com/docs/5.3#installing-laravel should pretty much cover it. In addition to that, you also need a relatively recent version of python. Also, in addiotion to coposer, 'npm install' and the 'update.sh' script must be run.

**Comment by rin1015** [comment]
Thank you :)
