### ISSUE TITLE
Can't scrape anime

### ISSUE THREAD

**Issue by tossmeboy** [Wicloz/Anime-Sentinel#3]
I try to scrape anime by starting a queue:work but it always returns with "No episodes found" I have put my username and pass into the .env but it still doesn't work. Any tips?

**Comment by Wicloz** [comment]
For the MAL username and password you have to enter your actual username and password. For the kissanime field you need to enter the cookies that kissanime give you, they look something like this: KISSANIME_USER="kV9SRW%2fZraoO0hm2pEp2AA%3d%3d"

**Comment by tossmeboy** [comment]
How do I find the cookies? I am using chrome. I clicked on the info icon next to the http://, and It brought up the cookies for it. I put those in but it still comes up with the "No episodes found" message.

**Comment by Wicloz** [comment]
These cookies: https://wicloz.stackstorage.com/index.php/s/6JdT1xu4E19GSjm
Get the string after 'content:' and put it between the "s.

**Comment by Wicloz** [comment]
Also, please update to the latest master because some disqus urls are now directing to localhost

**Comment by tossmeboy** [comment]
Updated, and it still doesn't work =( is there a way to check the link w/ my cookies?
e.g. http://kissanime.to/...

**Comment by Wicloz** [comment]
I've decided to put my own cookies in the .env.example so you con try those:
KISSANIME_USER="WJW422zyM2EFNv16LrEaptn2UCPeHgOdVvLT7EnijsA%3d"
KISSANIME_USER="WJW422zyM2EFNv16LrEaptn2UCPeHgOdVvLT7EnijsA%3d"
KISSANIME_PASS="tr%2fYJpbgbHHE4eblk%2fM2C%2bpsHTF6v%2bPnQ8ejCFEzYWQ%3d"
KISSCARTOON_USER="V%2b2ENEgO533%2bj4IBNcFka%2bk%2f229A5ZUYP%2fu55%2fNXGXg%3d"
KISSCARTOON_PASS="KCWhaaETxpRfKMfqatXxqzpWch7sP9YGltR0DAvVzrA%3d"

**Comment by Wicloz** [comment]
Rather than the cookies not working, did you start the queue listener? Since that is what checks for videos: "(sudo --user=www-data --group=www-data) php artisan queue:work --queue=periodic_high,periodic_low,high,default,low --timeout=0 --tries=1"

**Comment by tossmeboy** [comment]
So even when using your cred. it still comes up with no episodes found. I imagine this is on my end, so is it a dependency? I really wish laravel had a good logging system...

**Comment by Wicloz** [comment]
Something else I just thought about, did you seed the database? (php artisan db:seed) since streaming sites are defined there. Otherwise, try looking at anime from this season and see if you do see results from animeshow.

**Comment by tossmeboy** [comment]
-_- I am sorry for bothering you xD Thank you!

**Comment by tossmeboy** [comment]
By the way, I didn't seed the database
